---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  labels:
    app: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  ports:
    # the port that this service should serve on
  - port: 55680
    targetPort: 55680
  selector:
    app: opentelemetry-collector

