---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: sls-registry.cn-beijing.cr.aliyuncs.com/sls-microservices/front-end:v0.1.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: OTLP_ENDPOINT
          value: opentelemetry-collector.opentelemetry-collector:55680
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux

