---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: sls-registry.cn-beijing.cr.aliyuncs.com/sls-microservices/load-test:v0.1.0
        command: ["/usr/local/bin/runLocust.sh"]
        args: ["-c", "1", "-r", "1", "-h", "sock-shop.c0ae5df15fbf34b47ba3a9684e6ee2bee.cn-beijing.alicontainer.com"]
      nodeSelector:
        beta.kubernetes.io/os: linux
