---
apiVersion: v1
kind: Service
metadata:
  name: logtail
  labels:
    name: logtail
  namespace: logtail
spec:
  ports:
    # the port that this service should serve on
  - port: 11800
    targetPort: 11800
  selector:
    name: logtail
